# Generated by Django 4.2.3 on 2023-07-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorials', '0004_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='id',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapterNo',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
